### ISSUE TITLE
commenting test 

### ISSUE THREAD

**Issue by Bentlybro** [Bentlybro/Git-Discord-Bot#15]
test comments from github to discord and discord to github

**Comment by Git-Discord** [comment]
bentlybro: hello there

 - Posted By The Git-Discord Bot

**Comment by Bentlybro** [comment]
this is a comment

**Comment by Bentlybro** [comment]
embedded?

**Comment by Git-Discord** [comment]
bentlybro: message

 - Posted By The Git-Discord Bot

**Comment by Bentlybro** [comment]
msg

**Comment by Git-Discord** [comment]
bentlybro: test

 - Posted By The Git-Discord Bot

**Comment by Bentlybro** [comment]
lets goooo

**Comment by Bentlybro** [comment]
Dear [Recipient],

I hope this letter finds you in good health and high spirits. As I sit down to write these words, I am filled with a sense of excitement and nostalgia, reminiscing about all the beautiful moments we've shared and looking forward to the many more we will create together.

Life has a way of taking us on unexpected journeys, and it is during these moments that we often find solace in the presence of loved ones. You have been a constant source of support, encouragement, and love throughout my life's ups and downs, and for that, I am eternally grateful.

In a world that sometimes feels chaotic and uncertain, knowing that I can turn to you for guidance and a listening ear brings immense comfort to my heart. Your ability to empathize, understand, and offer wise advice is a testament to the beautiful soul you possess.

From the laughter-filled days of our childhood to the profound conversations we now share as adults, our bond has grown stronger and deeper with each passing year. I cherish the memories we've created together and look forward to making many more in the future.

No matter the distance or time that may separate us physically, I know that our hearts will always be connected. Our friendship transcends any boundaries, and I am grateful for the technology that allows us to stay in touch even when life takes us to different corners of the world.

The thought of your smile brings warmth to my soul, and your laughter is like a melody that fills the air with joy. Your kindness, generosity, and willingness to help others inspire me to be a better person every day. You have touched the lives of so many, and your positive influence knows no bounds.

I want you to know that you are not alone on this journey. Whenever you need someone to lean on, I will be there to offer my support, just as you have done for me countless times. Together, we can face any challenge that life throws our way and come out stronger on the other side.

As I conclude this lengthy letter, I want to express my deepest gratitude for being an incredible friend and a beacon of light in my life. You are a rare gem, and I am blessed to have you by my side. May our friendship continue to flourish and bring joy to both our hearts.

With all my love and admiration,

[Your Name]

**Comment by Bentlybro** [comment]
comment
